/**
 * AlphaZ  Api
 * AlphaZ Swagger Api
 *
 * OpenAPI spec version: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StateBean } from './stateBean';


export interface PrivilegeTreeView {
    children?: Array<PrivilegeTreeView>;
    data?: string;
    icon?: string;
    state?: StateBean;
    text?: string;
}
