/**
 * AlphaZ  Api
 * AlphaZ Swagger Api
 *
 * OpenAPI spec version: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrivilegeTreeView } from './privilegeTreeView';
import { RoleDTO } from './roleDTO';


/**
 * 角色菜单对应viewmodel
 */
export interface AllRoleMenuVIewModel {
    /**
     * 菜单操作对应model
     */
    menuOperation?: Array<PrivilegeTreeView>;
    /**
     * 角色列表
     */
    roleList?: Array<RoleDTO>;
}
