export * from './auditEventsMvcEndpoint.service';
import { AuditEventsMvcEndpointService } from './auditEventsMvcEndpoint.service';
export * from './authorizationEndpoint.service';
import { AuthorizationEndpointService } from './authorizationEndpoint.service';
export * from './checkTokenEndpoint.service';
import { CheckTokenEndpointService } from './checkTokenEndpoint.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './endpointMvcAdapter.service';
import { EndpointMvcAdapterService } from './endpointMvcAdapter.service';
export * from './environmentMvcEndpoint.service';
import { EnvironmentMvcEndpointService } from './environmentMvcEndpoint.service';
export * from './globalErrorController.service';
import { GlobalErrorControllerService } from './globalErrorController.service';
export * from './healthMvcEndpoint.service';
import { HealthMvcEndpointService } from './healthMvcEndpoint.service';
export * from './heapdumpMvcEndpoint.service';
import { HeapdumpMvcEndpointService } from './heapdumpMvcEndpoint.service';
export * from './indexController.service';
import { IndexControllerService } from './indexController.service';
export * from './loggersMvcEndpoint.service';
import { LoggersMvcEndpointService } from './loggersMvcEndpoint.service';
export * from './metricsMvcEndpoint.service';
import { MetricsMvcEndpointService } from './metricsMvcEndpoint.service';
export * from './priviligeController.service';
import { PriviligeControllerService } from './priviligeController.service';
export * from './tokenEndpoint.service';
import { TokenEndpointService } from './tokenEndpoint.service';
export * from './tokenKeyEndpoint.service';
import { TokenKeyEndpointService } from './tokenKeyEndpoint.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './whitelabelApprovalEndpoint.service';
import { WhitelabelApprovalEndpointService } from './whitelabelApprovalEndpoint.service';
export * from './whitelabelErrorEndpoint.service';
import { WhitelabelErrorEndpointService } from './whitelabelErrorEndpoint.service';
export const APIS = [AuditEventsMvcEndpointService, AuthorizationEndpointService, CheckTokenEndpointService, CustomerControllerService, EndpointMvcAdapterService, EnvironmentMvcEndpointService, GlobalErrorControllerService, HealthMvcEndpointService, HeapdumpMvcEndpointService, IndexControllerService, LoggersMvcEndpointService, MetricsMvcEndpointService, PriviligeControllerService, TokenEndpointService, TokenKeyEndpointService, UserControllerService, WhitelabelApprovalEndpointService, WhitelabelErrorEndpointService];
