/**
 * AlphaZ  Api
 * AlphaZ Swagger Api
 *
 * OpenAPI spec version: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuditEventsMvcEndpointService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * findByPrincipalAndAfterAndType
     * 
     * @param principal principal
     * @param after after
     * @param type type
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByPrincipalAndAfterAndTypeUsingGET(principal?: string, after?: Date, type?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public findByPrincipalAndAfterAndTypeUsingGET(principal?: string, after?: Date, type?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public findByPrincipalAndAfterAndTypeUsingGET(principal?: string, after?: Date, type?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public findByPrincipalAndAfterAndTypeUsingGET(principal?: string, after?: Date, type?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (principal !== undefined) {
            queryParameters = queryParameters.set('principal', <any>principal);
        }
        if (after !== undefined) {
            queryParameters = queryParameters.set('after', <any>after.toISOString());
        }
        if (type !== undefined) {
            queryParameters = queryParameters.set('type', <any>type);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/vnd.spring-boot.actuator.v1+json',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/auditevents`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findByPrincipalAndAfterAndType
     * 
     * @param principal principal
     * @param after after
     * @param type type
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByPrincipalAndAfterAndTypeUsingGET1(principal?: string, after?: Date, type?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public findByPrincipalAndAfterAndTypeUsingGET1(principal?: string, after?: Date, type?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public findByPrincipalAndAfterAndTypeUsingGET1(principal?: string, after?: Date, type?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public findByPrincipalAndAfterAndTypeUsingGET1(principal?: string, after?: Date, type?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (principal !== undefined) {
            queryParameters = queryParameters.set('principal', <any>principal);
        }
        if (after !== undefined) {
            queryParameters = queryParameters.set('after', <any>after.toISOString());
        }
        if (type !== undefined) {
            queryParameters = queryParameters.set('type', <any>type);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/vnd.spring-boot.actuator.v1+json',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/auditevents.json`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
