/**
 * AlphaZ  Api
 * AlphaZ Swagger Api
 *
 * OpenAPI spec version: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ResponseModel } from '../model/responseModel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * addUser
     * 
     * @param username 
     * @param password 
     * @param phone 
     * @param teamid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addUserUsingPOST(username?: string, password?: string, phone?: string, teamid?: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseModel>;
    public addUserUsingPOST(username?: string, password?: string, phone?: string, teamid?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseModel>>;
    public addUserUsingPOST(username?: string, password?: string, phone?: string, teamid?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseModel>>;
    public addUserUsingPOST(username?: string, password?: string, phone?: string, teamid?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (username !== undefined) {
            queryParameters = queryParameters.set('username', <any>username);
        }
        if (password !== undefined) {
            queryParameters = queryParameters.set('password', <any>password);
        }
        if (phone !== undefined) {
            queryParameters = queryParameters.set('phone', <any>phone);
        }
        if (teamid !== undefined) {
            queryParameters = queryParameters.set('teamid', <any>teamid);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<ResponseModel>(`${this.basePath}/user/new`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteUser
     * 
     * @param userid userid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteUserUsingDELETE(userid: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseModel>;
    public deleteUserUsingDELETE(userid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseModel>>;
    public deleteUserUsingDELETE(userid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseModel>>;
    public deleteUserUsingDELETE(userid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userid === null || userid === undefined) {
            throw new Error('Required parameter userid was null or undefined when calling deleteUserUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<ResponseModel>(`${this.basePath}/user/${encodeURIComponent(String(userid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * forgetPassword
     * 
     * @param username username
     * @param password password
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public forgetPasswordUsingPOST(username?: string, password?: string, observe?: 'body', reportProgress?: boolean): Observable<ResponseModel>;
    public forgetPasswordUsingPOST(username?: string, password?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseModel>>;
    public forgetPasswordUsingPOST(username?: string, password?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseModel>>;
    public forgetPasswordUsingPOST(username?: string, password?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (username !== undefined) {
            queryParameters = queryParameters.set('username', <any>username);
        }
        if (password !== undefined) {
            queryParameters = queryParameters.set('password', <any>password);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<ResponseModel>(`${this.basePath}/user/forgetpassword`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getMOByUser
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMOByUserUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseModel>;
    public getMOByUserUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseModel>>;
    public getMOByUserUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseModel>>;
    public getMOByUserUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getMOByUserUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ResponseModel>(`${this.basePath}/user/${encodeURIComponent(String(id))}/menu/op`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRoleByUser
     * 
     * @param username username
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRoleByUserUsingGET(username: string, observe?: 'body', reportProgress?: boolean): Observable<ResponseModel>;
    public getRoleByUserUsingGET(username: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseModel>>;
    public getRoleByUserUsingGET(username: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseModel>>;
    public getRoleByUserUsingGET(username: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (username === null || username === undefined) {
            throw new Error('Required parameter username was null or undefined when calling getRoleByUserUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ResponseModel>(`${this.basePath}/user/${encodeURIComponent(String(username))}/role`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateUser
     * 
     * @param userid userid
     * @param username 
     * @param password 
     * @param phone 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUserUsingPATCH(userid: number, username?: string, password?: string, phone?: string, observe?: 'body', reportProgress?: boolean): Observable<ResponseModel>;
    public updateUserUsingPATCH(userid: number, username?: string, password?: string, phone?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseModel>>;
    public updateUserUsingPATCH(userid: number, username?: string, password?: string, phone?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseModel>>;
    public updateUserUsingPATCH(userid: number, username?: string, password?: string, phone?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userid === null || userid === undefined) {
            throw new Error('Required parameter userid was null or undefined when calling updateUserUsingPATCH.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (username !== undefined) {
            queryParameters = queryParameters.set('username', <any>username);
        }
        if (password !== undefined) {
            queryParameters = queryParameters.set('password', <any>password);
        }
        if (phone !== undefined) {
            queryParameters = queryParameters.set('phone', <any>phone);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.patch<ResponseModel>(`${this.basePath}/user/${encodeURIComponent(String(userid))}`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
